[package]
name          = "test-case"
version       = "2.1.0"
edition       = "2018"
authors       = ["Marcin Sas-Szymanski <marcin.sas-szymanski@anixe.pl>", "Wojciech Polak <frondeus@gmail.com>", "Łukasz Biel <lukasz.p.biel@gmail.com>"]
description   = "Provides #[test_case(...)] procedural macro attribute for generating parametrized test cases easily"
keywords      = ["test", "case", "tests", "unit", "testing"]
categories    = ["development-tools", "development-tools::testing"]
readme        = "README.md"
license       = "MIT"
repository    = "https://github.com/frondeus/test-case"
documentation = "https://docs.rs/test-case"
exclude       = ["tests/snapshots/**/*"]

[features]
with-regex = ["regex", "test-case-macros/with-regex"]
for-each-file = ["test-case-macros/for-each-file"]
for-each-file-tracking = ["test-case-macros/for-each-file-tracking"]

[badges]
maintenance = { status = "actively-developed" }

[lib]
doctest    = false
path       = "src/lib.rs"

[dependencies]
test-case-macros = { version = "2.1.0", path = "crates/test-case-macros", default-features = false }
regex = { version = "1.5", optional = true }

[dev-dependencies]
insta       = "1.12"
itertools   = "0.10"
indexmap    = "1.8"
regex       = "1.5"

[workspace]
members = ["crates/*"]

[[test]]
name = "acceptance"
path = "tests/acceptance_tests.rs"
